### ISSUE TITLE
Building the site locally does not show the content

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/bitcointranscripts.github.io#34]
Following the README [instructions](https://github.com/bitcointranscripts/bitcointranscripts.github.io#installation-and-building-locally) to build the site locally results to a site without content. 

<img src="https://user-images.githubusercontent.com/18506343/152141711-74c44a4b-7c71-42a2-8861-b39d243cb958.png" width="500"  />

I am not sure why that might be the case but it seems to be related to the fact that the content in `./public/` is pre-build since everything works as expected after fetching the submodule as indicated in the [instructions here](https://github.com/bitcointranscripts/bitcointranscripts/issues/42#issuecomment-887674468) and building with `hugo`.

I have no prior experience with submodules but because git expects us to explicitly ask it to download the submodule’s content, I think that we should at least add another step to the build instructions to make it clear. 
I've played around with the commands and I think we could mention the   `git clone` `--recursive` flag that downloads everything, including any submodules and/or `git submodule update` that updates the submodule.

Also regarding what I said about the content in `./public/`. Does this have to be in source control? Because anybody that clones the repository can build that with the `hugo` command after fetching the submodule. It also adds ~100MB in the repository.

**Comment by adamjonas** [comment]
You are correct. @michaelfolkson has complained about this also. I just need to find the time to better document. My method is hacky and isn't how it should be done since I'm also no submodule expert.

Regarding the public folder, I agree that it doesn't need to be in source control and I'd gladly take a PR to that updates the gh action to build the project without it (which I believe the current script doesn't do).
