### ISSUE TITLE
Alphabetical sorting for new transcripts not working like it should

### ISSUE THREAD

**Issue by michaelfolkson** [bitcointranscripts/bitcointranscripts.github.io#45]
The most recently added transcripts are being added to the top of the page rather than being alphabetically sorted and similarly the directories with recently added transcripts are being moved to the top.

<img width="954" alt="Screenshot 2022-07-31 at 18 35 37" src="https://user-images.githubusercontent.com/16323900/182038587-75541f9c-c76a-417e-895f-def4e0d8b0e3.png">

**Comment by adamjonas** [comment]
this is due to dates being added in the front matter after #42. The alphabetical sorting returns if you remove the dates from those transcripts.

Date appears to be a reserved param and the readme doesn't suggest adding it to the front matter so I'm just removing them in https://github.com/bitcointranscripts/bitcointranscripts/pull/188
